### ISSUE TITLE
Support linux

### ISSUE THREAD

**Issue by prateekmedia** [bdlukaa/system_theme#2]
There is a plugin that is trying to get the theme's accent color and other colors for linux:
https://github.com/gtk-flutter/gtk_theme_fl

It can be used as a base to support linux for this plugin. Also as gtk doesn't support dark theme directly, we can use `theme_text_color` to know if the theme is dark or light.

**Comment by bdlukaa** [comment]
The reason linux isn't supported is because this is not available in its Kernel. There are so many Linux distros, and we can not pick one

**Comment by prateekmedia** [comment]
@bdlukaa Nope, there are many distro but flutter uses gtk for rendering the UI stuff.

And if a distro supports gtk then it will surely have a theme, whether it be default Adwaita or a custom one.

So this approach I mentioned above will work for any distro that supports gtk. If by any chance a distro doesnt support gtk at all then it will pick the default light theme with blue accent color.

**Comment by prateekmedia** [comment]
It is working (I recommend using `gtk-theme-fl` separately as It will be updated):
Gtk Theme Flutter:
![Screenshot_20211119_085327](https://user-images.githubusercontent.com/41370460/142560547-b8fb36b1-5125-47ea-affa-df9d40597c68.png)

Pamac using Adwaita-dark Gtk theme:
![Screenshot_20211119_090053](https://user-images.githubusercontent.com/41370460/142560532-baf062e9-02d8-4d25-a660-0eda25ca95f7.png)
