### ISSUE TITLE
[critical] `2.3.0` Breaks release build at runtime

### ISSUE THREAD

**Issue by kj415j45** [bdlukaa/system_theme#29]
[`2.3.0`](https://pub.dev/packages/system_theme/versions/2.3.0) Introduce changes in #7 , which provides ability for app for Windows to react with system accent color changes.

It should be an awesome updates, but, a mistake was made there. As per #28 mentioned, while trying to stream the accent color, cause `LateInitializationError`.

Beyond that, it actually break release build of other platform (At least `Web` and `Android` are breaking). For debug build, it works fine with console error, but all things works. However, in a release build,
this error can break the whole initialization phase and result a blank app without anything. It also makes web build hang up and finally being marked as no respond.

If I understand correctly:
https://github.com/bdlukaa/system_theme/blob/126cd20b59f124d4a2686353f52465b2d461dd24/lib/system_theme.dart#L59-L60
Here, try to initialize final variable `SystemTheme.accentColor` with `SystemAccentColor(fallbackColor)..load()`. During the `load()`,
https://github.com/bdlukaa/system_theme/blob/126cd20b59f124d4a2686353f52465b2d461dd24/lib/system_theme.dart#L137-L149
`SystemTheme.onChange` getter was called, and it `return Stream.value(accentColor)` on platform other than Windows.
https://github.com/bdlukaa/system_theme/blob/126cd20b59f124d4a2686353f52465b2d461dd24/lib/system_theme.dart#L74-L80
The variable `accentColor` should be evaluate immediately, and it actually means `SystemTheme.accentColor`, which is still initializing. Then cause `LateInitializationError`.

Here's my current investigation report. I'm not sure why it will make web build no respond as it should be failed or crash at start time, there may be other deeper issue.

**Comment by longfit** [comment]
I have tested system_theme example at flutter 3.10.6
on platform 
1 .Chrome  fail ( show Error: LateInitializationError: accentColor) but shown unexpected result
2. windows Success 
3. Android fail  show Error: LateInitializationError: accentColor)
4. Linux fail  ( pause on exception)

**Comment by bdlukaa** [comment]
The solution may be just subscribe to the `onChange` stream after resolving the colors
