### ISSUE TITLE
[QUESTION] How does it work on iOS??

### ISSUE THREAD

**Issue by neoapps-dev** [bdlukaa/system_theme#36]
As much as i know, iOS doesn't have system accent,
so how does it work?

**Comment by bdlukaa** [comment]
There indeed isn't a system accent color on iOS. Instead, you can set it at the application level by specifying an accent color in your app's asset catalog. The color returned on iOS is this color.

This is usually useful to the ones that use Flutter's add-to-app feature.

**Comment by neoapps-dev** [comment]
ooo ok thank you :)
