### ISSUE TITLE
Depreciation in windows10colors causes build failure

### ISSUE THREAD

**Issue by theAeon** [bdlukaa/system_theme#5]
In line 66 of windows/system_theme_plugin.cpp, `windows10colors::GetDarkModeEnabled(darkMode);` raises a warning, causing the build to fail.

For some reason the dev of the dependency decided to replace it with `GetAppDarkModeEnabled` with identical functionality. Works fine when replaced.

**Comment by hs-dev1** [comment]
thanks

**Comment by Ali-Fadaei** [comment]
We have same problem!  😪
