### ISSUE TITLE
fatal error C1083:can not open the file "SystemTheme/Windows10Colors-master/Windows10Colors/Windows10Colors.cpp"

### ISSUE THREAD

**Issue by qlshouyu** [bdlukaa/system_theme#8]
Run command "flutter build windows"; My system is window10 19042.685;
fatal error C1083: 无法打开包括文件: “SystemTheme/Windows10Colors-master/Windows10Colors/Windows10Colors.cpp”: No such file or directory [**\build\windows\plugins\system_theme\system_theme_plugin.vcxproj]

**Comment by bdlukaa** [comment]
`flutter run` must be executed at least once before building

**Comment by jinzw1993** [comment]
We have same problem! 😪

**Comment by bdlukaa** [comment]
Could you provide your `flutter doctor -v`?

**Comment by jinzw1993** [comment]
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [版本 10.0.19043.1645], locale zh-CN)
    • Flutter version 3.0.0 at D:\flutter\flutter3\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (7 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\Sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.0)
    • Visual Studio at D:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32505.173
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\android-studio-bu
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Android Studio (version 4.2)
    • Android Studio at D:\ASs\android-studio-ide-192.6392135-windows\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Android Studio (version 2020.3)
    • Android Studio at D:\ASs\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Android Studio (version 2021.1)
    • Android Studio at D:\ASs\android-studio-ide-2021\android-studio-2021.1.1.5-windows\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 212.4746.57

[√] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at D:\Program Files\JetBrains\IntelliJ IDEA 2021.3
    • Flutter plugin version 67.1.4
    • Dart plugin version 221.5591.52

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.19043.1645]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 101.0.4951.54
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 101.0.1210.39

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by grislux55** [comment]
Check `<Your Project>\windows\flutter\ephemeral\.plugin_symlinks\system_theme\windows\SystemTheme`.
Clean up this directory and try to download [this](https://github.com/res2k/Windows10Colors) manually.
tips: the name of the package should be `Windows10Colors.zip` and CMake will extract it automatically.

**Comment by jinzw1993** [comment]
@grislux55 thanks. you are so professional。very very good！！！

**Comment by grislux55** [comment]
@bdlukaa Currently, we lose verification of downloaded repo. Maybe using git submodule can solve these problems?

**Comment by bdlukaa** [comment]
@grislux55 According to the [LICENSE](https://github.com/res2k/Windows10Colors/blob/master/Windows10Colors/LICENSE.txt) and the repo README, I guess we can copy these files into the project and use it without any extra steps.
